### ISSUE TITLE
Inconsistent performances between my inference and the paper metrics

### ISSUE THREAD

**Issue by fuzzy-raccoon** [franciszzj/Leffa#15]
Hi,
Thank you very much for your work !
I used the code provided in app.py to run inferences on VTONHD and DressCode. I obtained the following metrics on the test dresses from DressCode (paired), using the `virtual_tryon_dc.pth` weights file and your eval script : 

Here's the markdown code for the table:

```markdown
| PyTorch-FID | Clean-FID | Clean-KID | PSNR    | SSIM   | LPIPS  |
|------------|-----------|-----------|----------|---------|---------|
| 20.8264    | 20.6455   | 11.8604   | 17.9070 | 0.8561  | 0.0799 |
```
As you may see the FID seems very high.

For VTONHD, the difference is less important but still exists, I get the following metrics running your eval script : 
```markdown
| PyTorch-FID | Clean-FID | Clean-KID | PSNR    | SSIM   | LPIPS  |
|------------|-----------|-----------|----------|---------|---------|
| 5.3188     | 5.2426    | 0.1054    | 20.1114 | 0.8564  | 0.0647 |
```
Is there anything specific that should be modified in the eval script or with the `leffa_predict` function?

**Comment by franciszzj** [comment]
Thank you for your interest.
The models released are just demos. Both the mask generator and densepose generator adopt other solutions from the community, rather than the internal models used during training and testing. Therefore, there may be some performance differences.
Regarding the issue with DressCode, we have taken note of it and are currently investigating the cause. We appreciate you pointing it out.

**Comment by franciszzj** [comment]
@fuzzy-raccoon
For VITON-HD, please use the official agnostic mask provided by VITON-HD for testing.
For DressCode, please use the agnostic mask obtained from https://github.com/yisol/IDM-VTON/blob/main/inference_dc.py#L231 provided here for testing.
