### ISSUE TITLE
这个需要多大显存运行？

### ISSUE THREAD

**Issue by Jandown** [franciszzj/Leffa#3]
感谢开源
请问，这个需要多大显存运行，
4080 16G显存都报OOM了

**Comment by franciszzj** [comment]
Thank you for your interest.
To fully run this project (including both virtual try-on and pose transfer), 38GB of vRAM is required. This is because both models need to be loaded onto the GPU simultaneously.
If you only want to run one model, you can comment out the other model in the code.
If you run only the virtual try-on model, 16GB of VRAM should be sufficient.

**Comment by franciszzj** [comment]
You can refer to the modifications here: https://github.com/franciszzj/Leffa/issues/1#issuecomment-2541954529

**Comment by Jandown** [comment]
> You can refer to the modifications here: [#1 (comment)](https://github.com/franciszzj/Leffa/issues/1#issuecomment-2541954529)

Thank you very much for your answer. It would be great if CPU uninstallation could be supported. Only 8GB of graphics memory is needed to run, which can meet the needs of more low-end graphics card users

**Comment by franciszzj** [comment]
Thank you for your suggestion.  
Currently, for faster inference, CPU uninstallation has not been used. We will improve this in the future.  
Additionally, please note that all the models are trained using open-source datasets (VITON-HD for virtual try-on and DeepFashion for pose transfer). Therefore, please ensure compliance with the respective dataset guidelines when using them. Thank you.
